# Generated by Django 4.2.30 on 2026-05-12 13:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="StockDailyData",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("symbol", models.CharField(db_index=True, max_length=20)),
                ("date", models.DateField(db_index=True)),
                ("change", models.FloatField(default=0.0)),
                ("change_percent", models.FloatField(default=0.0)),
                ("close_price", models.FloatField()),
                ("turnover", models.FloatField(default=0.0)),
                ("volume", models.BigIntegerField(default=0)),
                ("trade_count", models.IntegerField(default=0)),
                ("open_price", models.FloatField(default=0.0)),
                ("high_price", models.FloatField(default=0.0)),
                ("low_price", models.FloatField(default=0.0)),
            ],
            options={
                "ordering": ["-date"],
                "indexes": [
                    models.Index(
                        fields=["symbol", "date"], name="stock_analy_symbol_8533c5_idx"
                    )
                ],
                "unique_together": {("symbol", "date")},
            },
        ),
    ]
